### ISSUE TITLE
Allow user to indicate which folder to host the generated documentation

### ISSUE THREAD

**Issue by uglow** [swanky-docs/generator-swanky#19]
Currently the generator places files in the root directory of your application. It should ask you (with a default of 'docs'?) which folder to place the documentation code in.

**Comment by rodleviton** [comment]
@uglow Is it fair to assume a separate relative path config for local development and prod output?

E.g. Local dev could be built and served from 'docs' folder (by default) and when built the site may be configured to serve from root '/' or subfolder?

I am thinking `'srcDir'` (local) and `'serverPath'` (prod) to specify root or subdirectory option.

__Defaults__
`'srcDir': 'docs'`
`'serverPath': '/'`
