### ISSUE TITLE
Generated site does not look like sample site

### ISSUE THREAD

**Issue by uglow** [swanky-docs/generator-swanky#20]
Currently, the Yeoman generator produces a site that is not as nice as the sample site.

- [ ] Update generator to take advantage of latest sample site templates
- [ ] If site themes were going to be supported, maybe have a question asking which theme to use (and add the current them as the default)

**Comment by rodleviton** [comment]
@uglow I am currently working on a branch to update the default theme in the generator as well as an option to produce some 'Demo' assets. Will commit shortly. Site themes will be supported in the future option now is only default theme but there is a configuration option to add your own theme and templates.
