### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by rodleviton** [swanky-docs/generator-swanky#24]
Ok guys @leonardoanalista @Nighthawk14 @uglow I need your help deciding on a logo (important I know). The three candidates so far are: 

---
__Option A__
![logo-01](https://cloud.githubusercontent.com/assets/1480083/16915944/b91166a2-4d3d-11e6-9da0-21e8eba36bbc.png)

---
__Option B__
![logo-02](https://cloud.githubusercontent.com/assets/1480083/16915949/bd2a2f3a-4d3d-11e6-8c4d-87d26b1a116c.png)

---
__Option C__
![logo-03](https://cloud.githubusercontent.com/assets/1480083/16915952/c08c0bda-4d3d-11e6-86f4-7e61235a1691.png)

---

**Comment by leonardoanalista** [comment]
I like option c.

**Comment by uglow** [comment]
C too

**Comment by Nighthawk14** [comment]
I like the typo of B. In terms of graphics my ranking is : A - C - B 👍

**Comment by leonardoanalista** [comment]
My reasons:
If you think about the icons A and B alone, without the text, I can't visualize a 'S' in there. 'B' looks more like a number eight in my opinion.

**Comment by uglow** [comment]
I like the type style for the DOCS text in B.

**Comment by aniallator8** [comment]
Logo A is my fav but it needs to be much simpler and more recognisable.
I also think swanky says 'gold' and 'crown jewels' (in a sort of ridiculously over the top way ;)
Font used on A is nice too.

**Comment by rodleviton** [comment]
And the winner is...

![swanky logo](https://cloud.githubusercontent.com/assets/1480083/17762080/55ddf1ec-6550-11e6-84ea-01640489902d.png)

For this week anyway. Thanks for all your feedback.

**Comment by Nighthawk14** [comment]
Hey @rodleviton this one is awesome, love it!

**Comment by aniallator8** [comment]
Tasty logo. Very modern colours. Groovy
